export const IPC_CHANNELS = {
  AUTH_LOGIN: 'auth:login',
  AUTH_LOGOUT: 'auth:logout',
  AUTH_VERIFY_MANAGER_PIN: 'auth:verify-manager-pin',
  AUTH_GET_SESSION: 'auth:get-session',

  PRODUCT_SEARCH: 'product:search',
  PRODUCT_GET: 'product:get',
  PRODUCT_CREATE: 'product:create',
  PRODUCT_UPDATE: 'product:update',
  PRODUCT_BARCODE_LOOKUP: 'product:barcode-lookup',
  PRODUCT_IMPORT_CSV: 'product:import-csv',
  PRODUCT_LIST: 'product:list',
  PRODUCT_ARCHIVE: 'product:archive',
  PRODUCT_SEED_DEMO: 'product:seed-demo',
  PRODUCT_ADVANCED_SEARCH: 'product:advanced-search',
  PRODUCT_HISTORY: 'product:history',
  CATEGORY_LIST: 'category:list',
  CATEGORY_CREATE: 'category:create',
  CATEGORY_UPDATE: 'category:update',

  SALE_CREATE: 'sale:create',
  SALE_HOLD: 'sale:hold',
  SALE_RESUME: 'sale:resume',
  SALE_DISCARD_HELD: 'sale:discard-held',
  SALE_VOID: 'sale:void',
  SALE_GET: 'sale:get',
  SALE_LIST: 'sale:list',
  SALE_LOOKUP: 'sale:lookup',
  SALE_RECEIPT_PREVIEW: 'sale:receipt-preview',
  SALE_UPDATE: 'sale:update',

  SETTINGS_GET: 'settings:get',
  SETTINGS_GET_ALL: 'settings:get-all',
  SETTINGS_SET: 'settings:set',
  SETTINGS_LIST_PRINTERS: 'settings:list-printers',

  SYNC_STATUS: 'sync:status',
  SYNC_QUEUE_LIST: 'sync:queue-list',

  PRINT_RECEIPT: 'print:receipt',
  PRINT_TEST_RECEIPT: 'print:test-receipt',
  PRINT_TEST_LABEL: 'print:test-label',
  PRINT_Z_REPORT: 'print:z-report',
  LABEL_TEMPLATES: 'label:templates',
  LABEL_PRINT_BATCH: 'label:print-batch',
  REPORT_DAILY_SALES: 'report:daily-sales',
  REPORT_EOD: 'report:eod',
  REPORT_SALES_BY_CATEGORY: 'report:sales-by-category',
  REPORT_TOP_PRODUCTS: 'report:top-products',
  REPORT_PAYMENT_BREAKDOWN: 'report:payment-breakdown',
  REPORT_INVENTORY_VALUATION: 'report:inventory-valuation',
  REPORT_INVENTORY: 'report:inventory',
  REPORT_PROFIT: 'report:profit',

  RETURN_CREATE: 'return:create',
  RETURN_LIST: 'return:list',
  RETURN_GET: 'return:get',

  INVENTORY_ADJUST: 'inventory:adjust',
  INVENTORY_LOW_STOCK: 'inventory:low-stock',
  INVENTORY_MOVEMENTS: 'inventory:movement-history',

  CASH_SHIFT_START: 'cash:shift-start',
  CASH_SHIFT_END: 'cash:shift-end',
  CASH_SHIFT_CURRENT: 'cash:shift-current',
  CASH_SHIFT_LIST: 'cash:shift-list',
  CASH_SHIFT_GET: 'cash:shift-get',
  EOD_CLOSE_DAY: 'eod:close-day',
  EOD_CLOSINGS_LIST: 'eod:closings-list',
  EOD_CLOSING_GET: 'eod:closing-get',

  BACKUP_CREATE: 'backup:create',
  BACKUP_RESTORE: 'backup:restore',
  BACKUP_LIST: 'backup:list',

  VENDOR_LIST: 'vendor:list',
  VENDOR_CREATE: 'vendor:create',
  VENDOR_UPDATE: 'vendor:update',

  PO_CREATE: 'po:create',
  PO_LIST: 'po:list',
  PO_GET: 'po:get',
  PO_UPDATE_STATUS: 'po:update-status',
  PO_RECEIVE: 'po:receive',
  PO_REORDER_SUGGESTIONS: 'po:reorder-suggestions',

  GRN_CREATE: 'grn:create',
  GRN_LIST: 'grn:list',
  GRN_GET: 'grn:get',
  GRN_FINALIZE: 'grn:finalize',
  GRN_UPDATE: 'grn:update',
  GRN_CANCEL: 'grn:cancel',
  GRN_VOID: 'grn:void',

  SUPPLIER_PAYMENT_LIST: 'supplier-payment:list',
  SUPPLIER_PAYMENT_CREATE: 'supplier-payment:create',
  SUPPLIER_PAYMENT_UPDATE: 'supplier-payment:update',
  SUPPLIER_PAYMENT_DELETE: 'supplier-payment:delete',
  SUPPLIER_BALANCE: 'supplier-payment:balance',
  SUPPLIER_LEDGER: 'supplier-payment:ledger',

  CUSTOMER_SEARCH: 'customer:search',
  CUSTOMER_LIST: 'customer:list',
  CUSTOMER_CREATE: 'customer:create',
  CUSTOMER_UPDATE: 'customer:update',
  CUSTOMER_GET: 'customer:get',
  LOYALTY_RULES: 'customer:loyalty-rules',

  PROMOTION_LIST: 'promotion:list',
  PROMOTION_CREATE: 'promotion:create',
  PROMOTION_UPDATE: 'promotion:update',
  PROMOTION_PREVIEW: 'promotion:preview',

  GIFT_CARD_LIST: 'gift-card:list',
  GIFT_CARD_LOOKUP: 'gift-card:lookup',
  GIFT_CARD_ISSUE: 'gift-card:issue',
  GIFT_CARD_RELOAD: 'gift-card:reload',
  GIFT_CARD_DEACTIVATE: 'gift-card:deactivate',

  EXPENSE_CATEGORIES: 'expense:categories',
  EXPENSE_CREATE: 'expense:create',
  EXPENSE_LIST: 'expense:list',
  EXPENSE_APPROVE: 'expense:approve',

  AUDIT_LIST: 'audit:list',

  STOCKTAKE_START: 'stocktake:start',
  STOCKTAKE_CURRENT: 'stocktake:current',
  STOCKTAKE_COUNT: 'stocktake:count',
  STOCKTAKE_COMPLETE: 'stocktake:complete',
  STOCKTAKE_LIST: 'stocktake:list',
  STOCKTAKE_CANCEL: 'stocktake:cancel',

  STAFF_LIST: 'staff:list',
  STAFF_CREATE: 'staff:create',
  STAFF_UPDATE: 'staff:update',

  RECEIPT_TEMPLATES: 'template:receipt-list',
  RECEIPT_TEMPLATE_UPDATE: 'template:receipt-update',
  LABEL_TEMPLATE_UPDATE: 'template:label-update',
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
